# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '',
                'doc_host': 'www.nenadbozinovic.com',
                'git_url': 'https://github.com/nesaboz/blog',
                'lib_path': 'blog'},
  'syms': {}}
