# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/blog',
                'doc_host': 'https://nesaboz.github.io',
                'git_url': 'https://github.com/nesaboz/blog',
                'lib_path': 'blog'},
  'syms': {}}
