project:
  type: website

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto
  
website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  favicon: favicon.ico
  sidebar:
    style: docked
  navbar:
    background: primary
    search: true
    collapse-below: lg
    left:
      - text: Projects
        file: projects.ipynb
      - text: Mini-projects
        file: mini-projects.ipynb
      - text: Tips
        file: tips.ipynb
      - text: Media
        file: media.ipynb
    right:
      - icon: github
        href: https://github.com/nesaboz
      - icon: twitter
        href: https://twitter.com/nesaboz
        aria-label: Twitter
      - icon: linkedin
        href: https://www.linkedin.com/in/nenadbozinovic/
        aria-label: Linkedin

metadata-files: [nbdev.yml, sidebar.yml]

comments:
  giscus:
    repo: nesaboz/blog
    repo-id: R_kgDOI-Xebw
    category: Announcements
    category-id: DIC_kwDOI-Xeb84CUjh-
    mapping: pathname
    loading: lazy
    input-position: bottom
