# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/pytorched',
                'doc_host': 'https://nesaboz.github.io',
                'git_url': 'https://github.com/nesaboz/pytorched',
                'lib_path': 'pytorched'},
  'syms': {'pytorched.original_step_by_step': {}, 'pytorched.step_by_step': {}}}
